services:
  - type: web
    name: django-web-service
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT
